name: Java CI with Gradle

on:
  push:
    branches: [ "master", "test" ]
  pull_request:
    branches: [ "master", "test" ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      DOCKER_HUB_REPO: moo
      DOCKER_HUB_NAME: beomshinkim
      DOCKER_HUB_USER: beomshinkim
      DOCKER_HUB_PASSWORD: cground12!@

    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Setup Gradle with cache
      uses: gradle/actions/setup-gradle@v4
      with:
        cache-read-only: false

    - name: Give gradlew permission
      run: chmod +x ./gradlew

    - name: Build with Gradle Wrapper
      run: ./gradlew mooAppBootJar --exclude-task test

      # Docker Build
    - name: Docker Build Image
      run: |
        docker build -t ${{ env.DOCKER_HUB_REPO }} .

      # Docker Hub Login
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ env.DOCKER_HUB_USER }}
        password: ${{ env.DOCKER_HUB_PASSWORD }}

      # Docker 이미지 태그 및 푸시
    - name: Build and Release to DockerHub
      env:
        NAME: ${{ env.DOCKER_HUB_NAME }}
        REPO: ${{ env.DOCKER_HUB_REPO }}
      run: |
        docker tag $REPO:latest $NAME/$REPO:latest
        docker push $NAME/$REPO:latest